### ISSUE TITLE
推送失败，不懂怎么回事，是wsky不行了吗，有没有大佬帮忙解答一下，咱也不是这个专业的

### ISSUE THREAD

**Issue by super-si** [leifengwl/JDRouterPush#13]
Run python JDRouterPush.py
  python JDRouterPush.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
    WSKEY: ***
    DEVICENAME: 
    RECORDSNUM: 
    SERVERPUSHKEY: ***
    TG_BOT_TOKEN: 
    TG_USER_ID: 
    BARK: 
    PUSHPLUS: ***
Traceback (most recent call last):
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 403, in <module>
    main()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 391, in main
    records_num = int(RECORDSNUM)
ValueError: invalid literal for int() with base 10: ''
Error: Process completed with exit code 1.

**Comment by Benjamin-an** [comment]
RECORDSNUM填写条数

**Comment by super-si** [comment]
不是默认填写7条吗？还要再重新填吗，而且这个和原来代码是一样的

**Comment by leifengwl** [comment]
很抱歉，这是我的失误，不填写默认是7条，引发这个错误是在转换的时候出现错误，原因是没有进行判断导致的，两个解决办法，同步下代码(已更新)或者添加变量RECORDSNUM

**Comment by super-si** [comment]
> 很抱歉，这是我的失误，不填写替换是7条，引发此错误是在转换的时候出现错误，原因是没有进行判断导致的，两个解决方法，同步下代码（已更新）或者添加变量记录数

十分感谢大佬，已经可以用了
