### ISSUE TITLE
sever酱推送有问题

### ISSUE THREAD

**Issue by topdcw** [leifengwl/JDRouterPush#15]
源码:
 params = {
        "text": text,
        "desp": desp
    }
    res = requests.post(url=server_push_url, params=params)
应更改为：
 params = {
        "title": text,
        "desp": desp
    }
    res = requests.post(url=server_push_url, data=params)

**Comment by leifengwl** [comment]
感谢提醒，确实写错了  应该是之前的get直接改了post忘记改传递参数，不过目前没有影响推送，我现在更正下

**Comment by topdcw** [comment]
嗯嗯
