### ISSUE TITLE
后续会支持企业微信推送吗？

### ISSUE THREAD

**Issue by aachuanga** [leifengwl/JDRouterPush#19]
大佬 希望后续可以支持企业微信推送

**Comment by super-si** [comment]
servier酱支持微信企业版推动，你可以到servier酱官网看一下

**Comment by aachuanga** [comment]
> servier酱支持微信企业版推动，你可以到servier酱官网看一下

但是server酱免费的每天只有5条推送

**Comment by leifengwl** [comment]
下次更新会添加

**Comment by leifengwl** [comment]
已支持企业微信  查看变量添加
