### ISSUE TITLE
更新之后 部分账号会出问题

### ISSUE THREAD

**Issue by sxx1314** [leifengwl/JDRouterPush#2]
- 只有3台一代jdc的账号正常。
- 还有一个朋友的账号带360v6的合作款，会报错。
```
欢迎使用JDRouterPush!
获取routerActivityInfo失败
获取routerActivityInfo失败
Traceback (most recent call last):
  File "JDRouterPush.py", line 267, in <module>
    main(WSKEY,SERVERPUSHKEY)
  File "JDRouterPush.py", line 260, in main
    resultDisplay(SERVERPUSHKEY)
  File "JDRouterPush.py", line 188, in resultDisplay
    satisfiedTimes = pointInfo["satisfiedTimes"]
KeyError: 'satisfiedTimes'
```

- 看了下就是新增的版本更新检测等的代码，临时解决办法可以直接屏蔽这些功能。
- 建议加一个mac判断，对于非官方的硬件的mac不使用除查询积分外的各种查询功能。
- 京东云 官方硬件mac范围  DC:D8:7C       

![Screenshot_20210303-131427](https://user-images.githubusercontent.com/8444252/109756280-9a09d500-7c22-11eb-8e6e-27e9135bdd50.jpg)

**Comment by sxx1314** [comment]
- 关于DC:D8:7C 这一段mac地址是否代表所有官方硬件
- 从ieee.org 最新数据查询得到 Beijing Jingdong Century Trading Co., LTD.  仅有这一段mac地址段别无分号，所以可以放心食用。

**Comment by leifengwl** [comment]
合作款机器无法使用api进行查询吗？我这只在官方机器上测试过，如果能提供合作款机器调用api后的结果这是最好的，更新前是否正常使用呢？另外代码目前也不严谨，没有考虑到访问失败后 部分数据没有获取到的情况，我会尽快修复！

**Comment by sxx1314** [comment]
> 合作款机器无法使用api进行查询吗？我这只在官方机器上测试过，如果能提供合作款机器调用api后的结果这是最好的，更新前是否正常使用呢？另外代码目前也不严谨，没有考虑到访问失败后 部分数据没有获取到的情况，我会尽快修复！

合作款没有版本更新检测之类的功能，所以访问失败了，因为合作款都是内置的京东云插件不是京东写的固件。未更新前只会提示 获取routerActivityInfo失败，更新之后就会有 satisfiedTimes 错误。

**Comment by leifengwl** [comment]
好的 ，我知道原因了， 谢谢你的回答，我将尽快发布修复版本

**Comment by sxx1314** [comment]
> 好的 ，我知道原因了， 谢谢你的回答，我将尽快发布修复版本

二代好像也没有satisfiedTimes这个字段
[#3](https://github.com/leifengwl/JDRouterPush/issues/3)

**Comment by liupeng3425** [comment]
> 好的 ，我知道原因了， 谢谢你的回答，我将尽快发布修复版本

嗯嗯，我刚刚没看到这个issue，新提了一个，dict获取值的时候用get方法给默认值就好了。
