### ISSUE TITLE
2代设备适配问题

### ISSUE THREAD

**Issue by liupeng3425** [leifengwl/JDRouterPush#3]
第188行，
https://github.com/leifengwl/JDRouterPush/blob/3bc74838a1c7099e7484b0b14b2863bf0b27be89/JDRouterPush.py#L188
建议改成:
`satisfiedTimes = pointInfo.get("satisfiedTimes", '不适用坐享其成计划')`

主要是我2代的AX1800似乎没有这个字段，如果没有，可以用get默认值来防止报错。

**Comment by sxx1314** [comment]
除了一代jdc  非官方合作款硬件和二代都没有这个字段。

**Comment by leifengwl** [comment]
问题已经修复了，貌似只有一代会有这个参数，所以当时没考虑那么多，抱歉哈，新版已经修复了，你们同步下代码试试

**Comment by liupeng3425** [comment]
> 问题已经修复了，貌似只有一代会有这个参数，所以当时没考虑那么多，抱歉哈，新版已经修复了，你们同步下代码试试

感谢哈，我自己在本地已经测试过了没啥问题。

**Comment by leifengwl** [comment]
好的😀
