### ISSUE TITLE
双插件只能显示一个插件信息吗？

### ISSUE THREAD

**Issue by name2008less** [leifengwl/JDRouterPush#38]
128G的双插件，只能显示插件B+信息。之前还以为是我缓存出了问题，清除缓存后，还是只能显示B+插件信息。
![856FDF9B-4BE1-4CE9-A5ED-0D4A198081CF](https://user-images.githubusercontent.com/18633798/116798112-0c157200-ab1f-11eb-9e4b-798700c77648.jpeg)
![3951D060-4D71-43AA-8E55-8D28E36001C1](https://user-images.githubusercontent.com/18633798/116798116-0f106280-ab1f-11eb-9a58-3f5459cdd732.png)

**Comment by leifengwl** [comment]
需要看下请求结果  你在JDServiceAPI.py文件的第116行处
`else:
                pcdn_list = data["pcdn_list"]`
添加一行代码如下：
`else:
                print("插件请求数据：",data["pcdn_list"])
                pcdn_list = data["pcdn_list"]`

你将运行后的结果发给我看下，设计到隐私的部分可以删除或用其它字符，并声明下

**Comment by name2008less** [comment]
> 需要看下请求结果 你在JDServiceAPI.py文件的第116行处
> `else: pcdn_list = data["pcdn_list"]`
> 添加一行代码如下：
> `else: print("插件请求数据：",data["pcdn_list"]) pcdn_list = data["pcdn_list"]`
> 
> 你将运行后的结果发给我看下，设计到隐私的部分可以删除或用其它字符，并声明下

@leifengwl 
欢迎使用JDRouterPush!
23
Request routerActivityInfo failed!
24
插件请求数据： [{'status': '正常', 'nickname': '插件B+', 'name': 'pcdncentaurs', 'cache_size': '7160120'}, {'status': '正常', 'nickname': '插件A', 'name': 'pcdniqiyi', 'cache_size': '7106592'}]
25
Server酱推送的SERVERPUSHKEY未设置!!
26
pushplus推送的PUSHPLUS未设置!!
27
Telegram推送的TG_BOT_TOKEN或者TG_USER_ID未设置!!
28
bark服务的bark_token未设置!!
29
企业微信应用消息推送成功!
30
标题-> 2021年05月02日到账积分:152
31
内容->
32
 
33
> 欢迎使用JDRouterPush!,如果您有更好的推送模板欢迎pr 
34

35
---
36
数据日期:2021-05-02
37
今日总收益:152
38
总可用积分:5074
39
绑定账户:jd_XXXXXX
40
设备总数:1
41
**设备信息如下:**
42

43
- 128G==>
44
    - 今日积分：152
45
    - 可用积分：5074
46
    - 总收积分：15074
47
    - 当前网速：↑0KB/s   ↓0KB/s
48
    - 当前IP：192.168.1.2
49
    - 当前模式：bridge
50
    - 固件版本：JDC - 2.3.14.r1911
51
    - 插件状态：正常
52
    - 插件版本：插件B+
53
    - 缓存大小：7.16GB
54
    - PCDN：pcdncentaurs
55
    - 在线时间：10天9小时5分钟2秒
56
    - 最近到期积分：23
57
    - 最近到期时间：2022-03-30 22:14:32
58
    - 最近7条记录：
59
        - 2021-05-01  积分收入：152
60
        - 2021-04-30  积分收入：168
61
        - 2021-04-29  积分收入：194
62
        - 2021-04-28  积分收入：166
63
        - 2021-04-27  积分收入：112
64
        - 2021-04-26  积分收入：138
65
        - 2021-04-25  积分收入：180

**Comment by leifengwl** [comment]
好的  这几天比较忙 我会尽快修复

**Comment by leifengwl** [comment]
已修复问题  请重新拉取

**Comment by name2008less** [comment]
已经ok了，感谢！
