### ISSUE TITLE
二代128G 无法获取 插件信息   方糖偶尔不会推送

### ISSUE THREAD

**Issue by yer2018** [leifengwl/JDRouterPush#47]
Run python JDRouterPush.py
欢迎使用JDRouterPush!
Request routerActivityInfo failed!
无法获取插件信息!
信息如下: 
Server酱推送成功!

**Comment by leifengwl** [comment]
无法获取插件信息，是没获取到相关数据，这需要抓包测试，由于我没有此机型没法抓包，如果你抓包后可以将相关数据发送给我分析，对于推送提示成功但没有推送，可能是上限导致也可能网络问题，推荐使用微信企业推送，推送较为准确
