### ISSUE TITLE
作者大大，能加入Telegram的推送支持吗

### ISSUE THREAD

**Issue by cvm3698** [leifengwl/JDRouterPush#5]
作者大大，能加入Telegram的推送支持吗

**Comment by leifengwl** [comment]
目前需求不多，所以暂不考虑，可自行扩展代码

**Comment by abe520** [comment]
https://github.com/linuswong-debug/JDRouterPush

**Comment by leifengwl** [comment]
目前由jointemp提供了Telegram推送，同步最新版即可
