### ISSUE TITLE
这几天不能显示具体插件类型A、B、C、D了

### ISSUE THREAD

**Issue by name2008less** [leifengwl/JDRouterPush#51]
欢迎使用JDRouterPush!
Request routerActivityInfo failed!
插件请求数据： [{'status': '正常', 'nickname': '插件X', 'name': '插件X', 'cache_size': '82041152'}]
插件请求数据： [{'status': '正常', 'nickname': '插件X', 'name': '插件X', 'cache_size': '56461356'}]

只能和APP上一样显示插件X

**Comment by leifengwl** [comment]
貌似是服务端相应就是这个，已经不显示了
