### ISSUE TITLE
昨天更新后，依旧有几率推送失败

### ISSUE THREAD

**Issue by name2008less** [leifengwl/JDRouterPush#54]
![17668057-DFAE-4BD0-A6C0-863FFD26B0A5](https://user-images.githubusercontent.com/18633798/125370483-1cfd2200-e3b1-11eb-9669-a4bcc5aa412e.jpeg)
![36F439DE-07FF-43F8-901E-D2238A02E689](https://user-images.githubusercontent.com/18633798/125370490-225a6c80-e3b1-11eb-84a4-f749ca04fcb8.png)

运行一直卡住，最后是我手动取消的，日志里也没有更多信息，新功能自定义ip段也没有设置。

**Comment by leifengwl** [comment]
这个日志中我无法判断是哪个问题导致，是有几率运行失败？能否复现

**Comment by name2008less** [comment]
@leifengwl 
![B481419B-3877-4DBB-9DE0-3D656B3D5603](https://user-images.githubusercontent.com/18633798/125869766-ec1d9662-fdd4-4b74-9033-ce7a48b8dce7.png)

![058F5278-47F8-43DA-92E9-F6B1802E80F1](https://user-images.githubusercontent.com/18633798/125869874-cfa666f5-2cf0-4241-b560-a5746b8e9a22.jpeg)

今天又复现了，日志无限循环

Run python JDRouterPush.py
2
  python JDRouterPush.py
3
  shell: /usr/bin/bash -e {0}
4
  env:
5
    pythonLocation: /opt/hostedtoolcache/Python/3.9.6/x64
6
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.6/x64/lib
7
    WSKEY: ***
8
    DEVICENAME: 
9
    RECORDSNUM: 
10
    SERVERPUSHKEY: 
11
    TG_BOT_TOKEN: 
12
    TG_USER_ID: 
13
    BARK: 
14
    PUSHPLUS: 
15
    ACCESSTOKEN: 
16
    CORPID: ***
17
    CORPSECRET: ***
18
    TOUSER: ***
19
    AGENTID: ***
20
    THUMB_MEDIA_ID: ***
21
    AUTHOR: ***
22
    NETWORK_SEGMENT: 
23
欢迎使用JDRouterPush!
24
Request routerActivityInfo failed!
25
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
26
准备重新执行...
27
欢迎使用JDRouterPush!
28
Request routerActivityInfo failed!
29
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
30
准备重新执行...
31
欢迎使用JDRouterPush!
32
Request routerActivityInfo failed!
33
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
34
准备重新执行...
35
欢迎使用JDRouterPush!
36
Request routerActivityInfo failed!
37
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
38
准备重新执行...
39
欢迎使用JDRouterPush!
40
Request routerActivityInfo failed!
41
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
42
准备重新执行...
43
欢迎使用JDRouterPush!
44
Request routerActivityInfo failed!
45
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
46
准备重新执行...
47
欢迎使用JDRouterPush!
48
Request routerActivityInfo failed!
49
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
50
准备重新执行...
51
欢迎使用JDRouterPush!
52
Request routerActivityInfo failed!
53
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
54
准备重新执行...
55
欢迎使用JDRouterPush!
56
Request routerActivityInfo failed!
57
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
58
准备重新执行...
59
欢迎使用JDRouterPush!
60
Request routerActivityInfo failed!
61
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
62
准备重新执行...
63
欢迎使用JDRouterPush!
64
Request routerActivityInfo failed!
65
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
66
准备重新执行...
67
欢迎使用JDRouterPush!
68
Request routerActivityInfo failed!
69
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
70
准备重新执行...
71
欢迎使用JDRouterPush!
72
Request routerActivityInfo failed!
73
出现错误： ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by leifengwl** [comment]
手动执行呢？每次都是这样吗？

**Comment by name2008less** [comment]
@leifengwl 
第一张图片有显示，手动执行也有概率卡住

**Comment by leifengwl** [comment]
不确定是否是设备网络问题，可以加个判断  指定循环次数，避免无限循环
