### ISSUE TITLE
有大哥教一下怎么让设备定时重启么

### ISSUE THREAD

**Issue by name2008less** [leifengwl/JDRouterPush#62]
账户下绑定了两个设备，因为光猫设定好了每隔3天定时重启一次，想让无线宝跟着光猫一起重启，但是APP上只能选择周几重启，功能对不上。刚好看到IP切换这块好像有重启的代码，能教一下怎么移植出来么？

**Comment by leifengwl** [comment]
详细代码看 JDServiceAPI.getControlDevice
