### ISSUE TITLE
卡无限重启的部分童鞋可以看这个pr

### ISSUE THREAD

**Issue by sxx1314** [leifengwl/JDRouterPush#68]
### 重点已经有设备完成坐享其成任务的
- 任务卡在 ```'NoneType' object is not subscriptable``` 无限重启
- https://github.com/leifengwl/JDRouterPush/pull/67

**Comment by name2008less** [comment]
大佬能帮写个定时重启的脚本么
[#62](https://github.com/leifengwl/JDRouterPush/issues/62) 

纯小白，研究了下，实在看不懂。
