### ISSUE TITLE
运行python JDRouterPush.py返回报错

### ISSUE THREAD

**Issue by dalant2019** [leifengwl/JDRouterPush#69]
大佬你好，

刚在黑群晖上面Docker部署了大佬您的项目，前面都还算顺利，但到了运行python JDRouterPush.py 这一步，返回错误如下：
root@python:~ $ python JDRouterPush.py
Traceback (most recent call last):
  File "/root/JDRouterPush.py", line 5, in <module>
    import GlobalVariable
  File "/root/GlobalVariable.py", line 71
    DEVICENAME = os.environ.get(XX55BB:JDC02_XX55BB)  # 设备名称 mac后6位:设置的名称，多个使用&连接
                                    ^
SyntaxError: invalid syntax

GlobalVariable.py 上面关于“”DEVICENAME“” 我是这样填写：
DEVICENAME = os.environ.get(xx55BB:JDC02_xx55BB)  # 设备名称 

请问是否格式不对呢？烦请大佬可以在百忙中指点一下，非常感激，另外祝你和家人国庆快乐

**Comment by dalant2019** [comment]
看使用说明 DEVICENAME为非必填，尝试将DEVICENAME 用#屏蔽掉但还是不行

会返回如下结果：
Traceback (most recent call last):
  File "/root/JDRouterPush.py", line 5, in <module>
    import GlobalVariable
  File "/root/GlobalVariable.py", line 63, in <module>
    WSKEY = os.environ.get(AAJguIV_AEAe4hnsglBf7KtDp3xcQgz5mVimQuFlTuDL3xc7FapMEiFbsjlBiNpcFNHEiXMtSMt0GC2OOC7xxxx_SGVfxxxx)  # 京东云无线宝中获取
NameError: name 'AAJguIV_AEAe4hnsglBf7KtDp3xcQgz5mVimQuFlTuDL3xc7FapMEiFbsjlBiNpcFNHEiXMtSMt0GC2OOC7xxxx_SGVfxxxx' is not defined


刚刚我在github上面Fork了您的项目，在上面执行一次工作流测试是正常的，微信也能收到相关的推送信息，怀疑是脚本格式有点问题，但是我看不懂程序代码，只能请教大佬了

**Comment by bigdeer** [comment]
这些变量是系统环境变量，你没有定义的话，直接赋值：
WSKEY ="AAJguIV_AEAe4hnsglBf7KtDp3xcQgz5mVimQuFlTuDL3xc7FapMEiFbsjlBiNpcFNHEiXMtSMt0GC2OOC7xxxx_SGVfxxxx" # 京东云无线宝中获取
