### ISSUE TITLE
"查询积分接口失败"

### ISSUE THREAD

**Issue by zhoudahong** [leifengwl/JDRouterPush#76]
是否现在已经失效了？我用的stream抓包，点击无线宝app的“积分管理”，会提示"查询积分接口失败"。

**Comment by leifengwl** [comment]
我一直在使用，没有发现问题

**Comment by mrchenxxx** [comment]
> 是否现在已经失效了？我用的stream抓包，点击无线宝app的“积分管理”，会提示"查询积分接口失败"。

用小黄鸟抓包安装证书再看看就会有了
